spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 857269545@qq.com #发送邮件的邮箱地址
    password: sutmlvyltjwsbajg #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  mvc:
    pathmatch:
      #swagger2配置
      matching-strategy: ant_path_matcher
  thymeleaf:
    cache: false
  devtools:
    restart:
      #需要实时更新的目录
      additional-paths: resources/**,static/**,templates/**
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation_project?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #关闭日志打印则用这个impl：org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl:  ${MYBATIS_PLUS_LOG_IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}







